# Generated by Django 4.1.7 on 2025-06-12 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                ("customer_id", models.CharField(max_length=128)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Awaiting Questionnaire", "Awaiting Questionnaire"),
                            ("Awaiting UBO", "Awaiting UBO"),
                            ("Incomplete", "Incomplete"),
                            ("Not Started", "Not Started"),
                            ("Offboarded", "Offboarded"),
                            ("Paused", "Paused"),
                            ("Rejected", "Rejected"),
                            ("Under Review", "Under Review"),
                        ],
                        max_length=128,
                        verbose_name="current_status",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("Bridge", "Bridge")],
                        max_length=128,
                        verbose_name="provider",
                    ),
                ),
                ("signed_agreement_id", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "International Customer",
                "verbose_name_plural": "International Customers",
                "db_table": "international_customer",
            },
        ),
    ]
