# Generated by Django 4.1.7 on 2025-06-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("international_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("Active", "Active"),
                    ("Awaiting Questionnaire", "Awaiting Questionnaire"),
                    ("Awaiting UBO", "Awaiting UBO"),
                    ("Incomplete", "Incomplete"),
                    ("Not Started", "Not Started"),
                    ("Offboarded", "Offboarded"),
                    ("Paused", "Paused"),
                    ("Rejected", "Rejected"),
                    ("Under Review", "Under Review"),
                ],
                default="N/A",
                max_length=128,
                verbose_name="current_status",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="provider",
            field=models.CharField(
                choices=[("Bridge", "Bridge")],
                default="Bridge",
                max_length=128,
                verbose_name="provider",
            ),
        ),
    ]
