# Generated by Django 4.1.7 on 2025-06-14 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("international_wallet", "0002_alter_customer_current_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account_owner_name",
                    models.CharField(
                        help_text="Full name of the person who owns the account.",
                        max_length=255,
                        verbose_name="Account Owner Name",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        help_text="The name of the financial institution.",
                        max_length=255,
                        verbose_name="Bank Name",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True,
                        help_text="An optional, user-defined name for the account.",
                        max_length=100,
                        null=True,
                        verbose_name="Account Nickname",
                    ),
                ),
                (
                    "account_number_encrypted",
                    models.TextField(
                        help_text="Encrypted local bank account number.",
                        verbose_name="Encrypted Account Number",
                    ),
                ),
                (
                    "iban_encrypted",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted International Bank Account Number (IBAN) for international transfers.",
                        null=True,
                        verbose_name="Encrypted IBAN",
                    ),
                ),
                (
                    "swift_bic_encrypted",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted Bank Identifier Code (SWIFT/BIC) for international transfers.",
                        null=True,
                        verbose_name="Encrypted SWIFT/BIC",
                    ),
                ),
                (
                    "routing_number_encrypted",
                    models.TextField(
                        help_text="Encrypted routing, sort code, or other country-specific bank code.",
                        verbose_name="Encrypted Routing Number",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N/A", "N/A"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("MXN", "MXN"),
                        ],
                        default="N/A",
                        max_length=128,
                        null=True,
                        verbose_name="currency",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Unknown", "Unknown"),
                            ("US", "US"),
                            ("Iban", "Iban"),
                            ("Clabe", "Clabe"),
                        ],
                        default="Unknown",
                        max_length=128,
                        null=True,
                        verbose_name="provider",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="international_wallet.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Bank Account",
                "verbose_name_plural": "External Bank Accounts",
                "db_table": "external_bank_account",
            },
        ),
    ]
