# Generated by Django 4.1.7 on 2025-06-14 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("international_wallet", "0003_externalbankaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternationalWalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "txn_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the transaction was created.",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The amount of the transaction.",
                        max_digits=19,
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The amount of the final transaction.",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "exchange_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The amount of the exchange fee.",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "developer_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The amount of the developer fee.",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "gas_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The amount of the gas fee.",
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "source_payment_rail",
                    models.CharField(
                        choices=[
                            ("ACH", "ACH"),
                            ("WIRE", "Wire"),
                            ("ACH_PUSH", "ACH Push"),
                            ("ACH_SAME_DAY", "ACH Same Day"),
                            ("ARBITRUM", "Arbitrum"),
                            ("AVALANCHE_C_CHAIN", "Avalanche C-Chain"),
                            ("BASE", "Base"),
                            ("BRIDGE_WALLET", "Bridge Wallet"),
                            ("ETHEREUM", "Ethereum"),
                            ("OPTIMISM", "Optimism"),
                            ("POLYGON", "Polygon"),
                            ("SEPA", "SEPA"),
                            ("SOLANA", "Solana"),
                            ("SPEI", "SPEI"),
                            ("STELLAR", "Stellar"),
                            ("SWIFT", "SWIFT"),
                            ("TRON", "Tron"),
                        ],
                        default="SWIFT",
                        max_length=20,
                    ),
                ),
                (
                    "source_currency",
                    models.CharField(
                        choices=[
                            ("DAI", "DAI"),
                            ("EUR", "EUR"),
                            ("EURC", "EURC"),
                            ("MXN", "MXN"),
                            ("PYUSD", "PYUSD"),
                            ("USDB", "USDB"),
                            ("USD", "USD"),
                            ("USDC", "USDC"),
                            ("USDT", "USDT"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "from_address",
                    models.CharField(
                        blank=True,
                        help_text="Source address, e.g., bank account number or crypto wallet address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "destination_payment_rail",
                    models.CharField(
                        choices=[
                            ("ACH", "ACH"),
                            ("WIRE", "Wire"),
                            ("ACH_PUSH", "ACH Push"),
                            ("ACH_SAME_DAY", "ACH Same Day"),
                            ("ARBITRUM", "Arbitrum"),
                            ("AVALANCHE_C_CHAIN", "Avalanche C-Chain"),
                            ("BASE", "Base"),
                            ("BRIDGE_WALLET", "Bridge Wallet"),
                            ("ETHEREUM", "Ethereum"),
                            ("OPTIMISM", "Optimism"),
                            ("POLYGON", "Polygon"),
                            ("SEPA", "SEPA"),
                            ("SOLANA", "Solana"),
                            ("SPEI", "SPEI"),
                            ("STELLAR", "Stellar"),
                            ("SWIFT", "SWIFT"),
                            ("TRON", "Tron"),
                        ],
                        default="SWIFT",
                        max_length=20,
                    ),
                ),
                (
                    "destination_currency",
                    models.CharField(
                        choices=[
                            ("DAI", "DAI"),
                            ("EUR", "EUR"),
                            ("EURC", "EURC"),
                            ("MXN", "MXN"),
                            ("PYUSD", "PYUSD"),
                            ("USDB", "USDB"),
                            ("USD", "USD"),
                            ("USDC", "USDC"),
                            ("USDT", "USDT"),
                        ],
                        default="USD",
                        max_length=10,
                    ),
                ),
                (
                    "to_address",
                    models.CharField(
                        blank=True,
                        help_text="Destination address, e.g., bank account number or crypto wallet address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "external_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for the external account.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "client_reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("FAILED", "Failed"),
                            ("AWAITING_FUNDS", "Awaiting Funds"),
                            ("IN_REVIEW", "In Review"),
                            ("FUNDS_RECEIVED", "Funds Received"),
                            ("PAYMENT_SUBMITTED", "Payment Submitted"),
                            ("PAYMENT_PROCESSED", "Payment Processed"),
                            ("CANCELED", "Canceled"),
                            ("ERROR", "Error"),
                            ("UNDELIVERABLE", "Undeliverable"),
                            ("RETURNED", "Returned"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("receipt_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "succeeded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the transaction succeeded.",
                        null=True,
                    ),
                ),
                (
                    "webhook_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Response from the webhook after processing the transaction.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="international_wallet.customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "International Wallet Transaction",
                "verbose_name_plural": "International Wallet Transactions",
                "db_table": "international_wallet_transaction",
                "ordering": ["-created_on"],
            },
        ),
    ]
