# Generated by Django 4.1.7 on 2025-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("international_wallet", "0004_internationalwallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="chain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Undefined", "Undefined"),
                    ("Base", "Base"),
                    ("Solana", "Solana"),
                ],
                default="Undefined",
                max_length=128,
                null=True,
                verbose_name="chain",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                help_text="The address of the customer on the blockchain.",
                max_length=128,
                null=True,
            ),
        ),
    ]
