# Generated by Django 4.1.7 on 2024-03-23 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="cost",
            new_name="price",
        ),
    ]
