# Generated by Django 4.1.7 on 2024-03-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_subscription_transaction_alter_subscription_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=350, max_digits=10),
            preserve_default=False,
        ),
    ]
