version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8009"
        ports:
            - "8009:8009"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - mailhog
#            - redis
#            - es
        networks:
            - folo-api

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        expose:
            - "5432"
        ports:
            - "5432:5432"
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - folo-api

    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - ./.envs/.local/.pgadmin
        ports:
            - "5050:5050"
        depends_on:
            - postgres
        networks:
            - folo-api

    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
            - "8025:8025"
        networks:
            - folo-api

#    redis:
#        image: redis:6-alpine
#        container_name: redis
#        networks:
#            - folo-api
#
#    celery_worker:
#        build:
#            context: .
#            dockerfile: ./docker/local/django/Dockerfile
#        command: /start-celeryworker
#        container_name: celery_worker
#        volumes:
#            - .:/app
#        env_file:
#            - ./.envs/.local/.django
#            - ./.envs/.local/.postgres
#        depends_on:
#            - redis
#            - postgres
#            - mailhog
#        networks:
#            - folo-api
#
#    flower:
#        build:
#            context: .
#            dockerfile: ./docker/local/django/Dockerfile
#        command: /start-flower
#        container_name: flower
#        volumes:
#            - .:/app
#        env_file:
#            - ./.envs/.local/.django
#            - ./.envs/.local/.postgres
#        ports:
#            - "5555:5555"
#        depends_on:
#            - redis
#            - postgres
#        networks:
#            - folo-api
#
#    nginx:
#        restart: always
#        depends_on:
#            - api
#        volumes:
#            - static_volume:/app/staticfiles
#            - media_volume:/app/mediafiles
#        build:
#            context: ./docker/local/nginx
#            dockerfile: Dockerfile
#        ports:
#            - "8080:80"
#        networks:
#            - folo-api

networks:
    folo-api:
        driver: bridge

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    static_volume:
    media_volume: