# Generated by Django 4.1.7 on 2025-01-01 17:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_type_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("allowed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Wallet Type",
                "verbose_name_plural": "Wallet Types",
            },
        ),
        migrations.RenameField(
            model_name="customerprofile",
            old_name="provider_customer_id",
            new_name="customer_id",
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "external_unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "wallet_id",
                    models.PositiveIntegerField(
                        help_text="A unique system-generated numeric identifier for the wallet. Possible values: >= 1.",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the Wallet. Possible values: >= 3 characters and <= 50 characters.",
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(50),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("virtual", "Virtual"), ("physical", "Physical")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                            ("CANCELED", "Canceled"),
                            ("CANCELLED", "Cancelled"),
                            ("BARRED", "Barred"),
                            ("PENDING", "Pending"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KES",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be a 3-letter ISO code.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The balance in the wallet in the currency of the wallet",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reservations",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The reservations placed on the wallet (uncommitted transactions).",
                        max_digits=20,
                    ),
                ),
                (
                    "friendly_id",
                    models.CharField(
                        blank=True,
                        help_text="A unique reference for a wallet used for deposits and other transactions.",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "organisation_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="The organisation who owns this wallet. If not provided, then the wallet must be owned by a customer and hence customerId should be provided.",
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        help_text="Additional configuration settings for the wallet.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="wallet.customerprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to="wallet.wallettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["-created"],
            },
        ),
    ]
