# Generated by Django 4.1.7 on 2025-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_wallettype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="A unique account number for the wallet.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
