# Generated by Django 4.1.7 on 2025-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_wallet_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="card_type",
            field=models.CharField(
                choices=[("virtual", "Virtual"), ("physical", "Physical")],
                default="virtual",
                max_length=20,
            ),
        ),
    ]
