# Generated by Django 4.1.7 on 2025-02-20 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_alter_wallet_card_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopUpTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.BigIntegerField(
                        help_text="Unique payment ID from DTB.", unique=True
                    ),
                ),
                (
                    "external_unique_id",
                    models.UUIDField(
                        help_text="Unique ID generated for the transaction.",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                            ("ERROR_PERM", "Error Permanent"),
                        ],
                        default="PENDING",
                        help_text="Transaction status: PENDING, SUCCESSFUL, or ERROR_PERM.",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount between 10 and 150,000.",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(150000),
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KES",
                        help_text="Currency code, e.g., KES.",
                        max_length=3,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the transaction.",
                        null=True,
                    ),
                ),
                (
                    "merchant_name",
                    models.CharField(help_text="Name of the merchant.", max_length=255),
                ),
                (
                    "payment_type",
                    models.CharField(
                        help_text="Payment type, e.g., EFT.", max_length=50
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        help_text="Timestamp when the transaction was created."
                    ),
                ),
                (
                    "extra_info",
                    models.JSONField(
                        blank=True,
                        help_text="Additional info as a JSON object.",
                        null=True,
                    ),
                ),
                (
                    "payment_instrument_info",
                    models.JSONField(help_text="Details about the payment instrument."),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Transaction fee.",
                        max_digits=20,
                    ),
                ),
                (
                    "error_description",
                    models.TextField(
                        blank=True,
                        help_text="Error description if status is ERROR_PERM.",
                        null=True,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Payment reference from DTB.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Associated customer.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topup_transactions",
                        to="wallet.customerprofile",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Associated wallet.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topup_transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "TopUp Transaction",
                "verbose_name_plural": "TopUp Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
