# Generated by Django 4.1.7 on 2025-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0005_topuptransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="topuptransaction",
            name="gateway",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="topuptransaction",
            name="gatewayTransactionId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
