# Generated by Django 4.1.7 on 2025-03-15 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0006_topuptransaction_gateway_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topuptransaction",
            old_name="gatewayTransactionId",
            new_name="gateway_transaction_id",
        ),
    ]
