# Generated by Django 4.1.7 on 2025-04-15 09:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "wallet",
            "0007_rename_gatewaytransactionid_topuptransaction_gateway_transaction_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="mpin",
            field=models.CharField(
                blank=True,
                help_text="4-6 digit PIN for securing wallet transactions",
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(6),
                    django.core.validators.RegexValidator(
                        message="MPIN must contain only digits.", regex="^\\d+$"
                    ),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "external_unique_id",
                    models.UUIDField(
                        help_text="Unique ID generated for the transaction.",
                        unique=True,
                    ),
                ),
                (
                    "external_reference_id",
                    models.CharField(
                        blank=True,
                        help_text="External reference ID from provider",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("WALLET_TO_WALLET", "Wallet to Wallet Transfer"),
                            ("WALLET_TO_MPESA", "Wallet to MPESA Transfer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount.",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Transaction fee.",
                        max_digits=20,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("gateway", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "deliver_to_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra_info", models.JSONField(blank=True, null=True)),
                (
                    "webhook_response",
                    models.JSONField(
                        blank=True,
                        help_text="Webhook response data for the transaction",
                        null=True,
                    ),
                ),
                (
                    "withdrawal_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID for MPESA withdrawals", null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.customerprofile",
                    ),
                ),
                (
                    "from_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_transactions",
                        to="wallet.wallet",
                    ),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_transactions",
                        to="wallet.wallet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
