# Generated by Django 4.1.7 on 2025-04-15 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0008_wallet_mpin_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="mpin",
            field=models.CharField(
                blank=True,
                help_text="4 digit PIN for securing wallet transactions",
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(4),
                    django.core.validators.MaxLengthValidator(4),
                    django.core.validators.RegexValidator(
                        message="MPIN must contain only digits.", regex="^\\d+$"
                    ),
                ],
            ),
        ),
    ]
