# Generated by Django 4.1.7 on 2025-05-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0011_alter_transaction_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="tracing_context",
            field=models.CharField(
                blank=True,
                help_text="Tracing context from provider for debugging",
                max_length=100,
                null=True,
            ),
        ),
    ]
