# Generated by Django 4.1.7 on 2025-05-28 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0012_transaction_tracing_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                    ("EXPIRED", "Expired"),
                    ("PARTIAL", "Partially Completed"),
                    ("REVERSED", "Reversed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("WALLET_TO_WALLET", "Wallet to Wallet Transfer"),
                    ("WALLET_TO_MPESA", "Wallet to MPESA Transfer"),
                    ("WALLET_TO_BANK", "Wallet to Bank Transfer"),
                    ("WALLET_TO_PESALINK", "Wallet to PesaLink Transfer"),
                    ("REFUND", "Refund Transaction"),
                    ("REVERSAL", "Transaction Reversal"),
                    ("ADJUSTMENT", "Administrative Adjustment"),
                    ("FEE", "Transaction Fee"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="BankBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        help_text="Name of the account holder", max_length=100
                    ),
                ),
                (
                    "account_number",
                    models.CharField(help_text="Bank account number", max_length=50),
                ),
                (
                    "bank_code",
                    models.CharField(
                        help_text="Bank code (e.g., 0068 for Equity)", max_length=10
                    ),
                ),
                (
                    "branch_code",
                    models.CharField(help_text="Branch code", max_length=10),
                ),
                (
                    "bank_name",
                    models.CharField(help_text="Name of the bank", max_length=100),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the branch",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly name for the beneficiary",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this beneficiary is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this beneficiary was used",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_beneficiaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Beneficiary",
                "verbose_name_plural": "Bank Beneficiaries",
                "ordering": ["-last_used", "-created_at"],
                "unique_together": {("user", "account_number", "bank_code")},
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="bank_beneficiary",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank beneficiary for bank transfers",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="wallet.bankbeneficiary",
            ),
        ),
    ]
