# Generated by Django 4.1.7 on 2025-07-16 07:24

from django.db import migrations, models
from django.db.models import Count


def cleanup_duplicate_customer_profiles(apps, schema_editor):
    """
    Clean up duplicate CustomerProfile records with the same customer_id.
    Keep the most recent one and delete the rest.
    """
    CustomerProfile = apps.get_model('wallet', 'CustomerProfile')
    
    # Find all customer_ids that have duplicates
    duplicates = (
        CustomerProfile.objects
        .values('customer_id')
        .annotate(count=Count('customer_id'))
        .filter(count__gt=1, customer_id__isnull=False)
    )
    
    print(f"Found {duplicates.count()} customer_ids with duplicate records")
    
    for duplicate in duplicates:
        customer_id = duplicate['customer_id']
        count = duplicate['count']
        
        print(f"Processing customer_id {customer_id} with {count} duplicates")
        
        # Get all profiles with this customer_id, ordered by creation date (newest first)
        profiles = CustomerProfile.objects.filter(customer_id=customer_id).order_by('-created_at')
        
        # Keep the first (newest) one, delete the rest
        profiles_to_keep = profiles.first()
        profiles_to_delete = profiles[1:]
        
        user_name = f"{profiles_to_keep.user.first_name} {profiles_to_keep.user.last_name}" if profiles_to_keep.user else 'N/A'
        print(f"  Keeping CustomerProfile ID {profiles_to_keep.id} (User: {user_name})")
        
        for profile in profiles_to_delete:
            user_name = f"{profile.user.first_name} {profile.user.last_name}" if profile.user else 'N/A'
            print(f"  Deleting CustomerProfile ID {profile.id} (User: {user_name})")
            
            # Before deleting, we need to handle any related objects
            # Update any Wallets that reference this profile to reference the kept profile
            profile.wallets.update(customer=profiles_to_keep)
            
            # Update any TopUpTransactions that reference this profile
            profile.topup_transactions.update(customer=profiles_to_keep)
            
            # Update any Transactions that reference this profile
            profile.transactions.update(customer=profiles_to_keep)
            
            # Now safe to delete the duplicate profile
            profile.delete()
        
        print(f"  Cleanup completed for customer_id {customer_id}")


def reverse_cleanup_duplicate_customer_profiles(apps, schema_editor):
    """
    Reverse operation - this cannot be undone as we've deleted data.
    """
    print("WARNING: Cannot reverse duplicate cleanup - data has been permanently deleted")
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0013_alter_transaction_status_and_more"),
    ]

    operations = [
        # Clean up duplicate data
        migrations.RunPython(
            cleanup_duplicate_customer_profiles,
            reverse_cleanup_duplicate_customer_profiles,
        ),
    ]
