# Generated by Django 4.1.7 on 2025-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0014_auto_20250716_0724"),
    ]

    operations = [
        # Add the unique constraint to customer_id
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
