# Generated by Django 4.1.7 on 2025-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0015_auto_20250716_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topuptransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESSFUL", "Successful"),
                    ("ERROR_PERM", "Error Permanent"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                help_text="Transaction status: PENDING, SUCCESSFUL, or ERROR_PERM.",
                max_length=20,
            ),
        ),
    ]
