# Generated by Django 4.1.7 on 2025-08-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0016_add_expired_status_to_topup"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletMovementCallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtb_transaction_id",
                    models.CharField(
                        help_text="DTB's unique transaction ID to prevent duplicate processing",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "external_unique_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Original external unique ID (without DB-/CR- prefix)",
                        null=True,
                    ),
                ),
                (
                    "external_reference_id",
                    models.CharField(
                        help_text="DTB prefixed reference (DB-/CR-xxxxx)",
                        max_length=100,
                    ),
                ),
                (
                    "wallet_id",
                    models.PositiveIntegerField(help_text="Wallet ID from webhook"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        help_text="DTB transaction type (tfr.debit, tfr.credit, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Movement amount (negative for debit, positive for credit)",
                        max_digits=20,
                    ),
                ),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wallet balance after this movement",
                        max_digits=20,
                    ),
                ),
                ("other_wallet_id", models.PositiveIntegerField(blank=True, null=True)),
                ("location", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "webhook_data",
                    models.JSONField(help_text="Complete webhook payload from DTB"),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topup_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_callbacks",
                        to="wallet.topuptransaction",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_callbacks",
                        to="wallet.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Movement Callback",
                "verbose_name_plural": "Wallet Movement Callbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="walletmovementcallback",
            index=models.Index(
                fields=["external_unique_id"], name="wallet_wall_externa_e4f09e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletmovementcallback",
            index=models.Index(
                fields=["wallet_id"], name="wallet_wall_wallet__efb698_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletmovementcallback",
            index=models.Index(
                fields=["dtb_transaction_id"], name="wallet_wall_dtb_tra_a85288_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletmovementcallback",
            index=models.Index(
                fields=["processed"], name="wallet_wall_process_21318d_idx"
            ),
        ),
    ]
