# Generated by Django 4.1.7 on 2025-10-10 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0017_add_wallet_movement_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('intent_id', models.CharField(max_length=100, unique=True)),
                ('sca_type', models.CharField(default='OTP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transfer_type', models.CharField(max_length=30)),
                ('transfer_payload', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sca_sessions', to='wallet.transaction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sca_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_sca_session',
            },
        ),
        migrations.AddIndex(
            model_name='scasession',
            index=models.Index(fields=['intent_id'], name='wallet_sca__intent__1556ba_idx'),
        ),
        migrations.AddIndex(
            model_name='scasession',
            index=models.Index(fields=['user', 'status'], name='wallet_sca__user_id_c50b42_idx'),
        ),
    ]
