# Generated by Django 4.1.7 on 2025-10-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0017_add_wallet_movement_callback"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCASession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "intent_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "sca_type",
                    models.CharField(
                        default="OTP",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        help_text="WALLET_TO_WALLET, WALLET_TO_MPESA, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "transfer_payload",
                    models.JSONField(
                        help_text="Original request payload",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sca_sessions",
                        to="wallet.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sca_sessions",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_sca_session",
                "verbose_name": "SCA Session",
                "verbose_name_plural": "SCA Sessions",
            },
        ),
        migrations.AddIndex(
            model_name="scasession",
            index=models.Index(
                fields=["intent_id"], name="wallet_sca_intent__b9f4e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scasession",
            index=models.Index(
                fields=["user", "status"], name="wallet_sca_user_st_8b7f4a_idx"
            ),
        ),
    ]
