# Generated by Django 4.1.7 on 2025-10-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_scasession_scasession_wallet_sca__intent__1556ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scasession',
            name='original_dtb_jwt',
            field=models.TextField(blank=True, help_text='Original DTB JWT used for the request that triggered SCA', null=True),
        ),
    ]
