# Generated by Django 4.1.7 on 2025-12-08 10:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_add_original_dtb_jwt_to_sca_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Added'), ('mobile_import', 'Mobile Contacts Import'), ('transaction', 'From Transaction')], default='manual', help_text='How this contact was added', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='name',
            field=models.CharField(blank=True, help_text='Contact name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number in E164 format (+254XXXXXXXXX)', max_length=20, region='KE'),
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['user', 'source'], name='wallet_user_user_id_38fb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontact',
            index=models.Index(fields=['user', '-last_used'], name='wallet_user_user_id_faa536_idx'),
        ),
    ]
