# Generated by Django 4.1.7 on 2025-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The exact time when the API request was initiated.",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="The relative or absolute URL endpoint of the API request (e.g., /v0/customers).",
                        max_length=255,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="The HTTP method used for the request (e.g., GET, POST, PUT, DELETE).",
                        max_length=10,
                    ),
                ),
                (
                    "request_headers",
                    models.JSONField(
                        default=dict,
                        help_text="JSON representation of the request headers sent.",
                    ),
                ),
                (
                    "request_body",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of the request body sent. Null if no body.",
                        null=True,
                    ),
                ),
                (
                    "response_status_code",
                    models.IntegerField(
                        blank=True,
                        help_text="The HTTP status code received in the API response (e.g., 200, 400, 500).",
                        null=True,
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of the response headers received.",
                        null=True,
                    ),
                ),
                (
                    "response_body",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of the response body received. Null if no body.",
                        null=True,
                    ),
                ),
                (
                    "response_time_ms",
                    models.FloatField(
                        blank=True,
                        help_text="The time taken for the API call in milliseconds.",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False,
                        help_text="True if the API call was successful (e.g., 2xx status code), False otherwise.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Any error message associated with a failed API call.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Log Entry",
                "verbose_name_plural": "API Log Entries",
                "db_table": "api_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
