# Generated by Django 4.1.7 on 2025-06-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_country_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="postal_code_format",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
