# Generated by Django 4.1.7 on 2025-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_country_postal_code_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="postal_code_format",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
