# Generated by Django 4.1.7 on 2025-06-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_country_name_alter_country_postal_code_format_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("code", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Occupation",
                "verbose_name_plural": "Occupations",
                "db_table": "occupation",
                "ordering": ["name"],
            },
        ),
    ]
