# Generated by Django 4.1.7 on 2024-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transunion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditreport",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="message_credit_risk_score",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="message_total_loan_outstanding",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="registration_response_code",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="risk_classification",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="tol",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="total_npa",
        ),
        migrations.RemoveField(
            model_name="creditreport",
            name="total_pa",
        ),
        migrations.AddField(
            model_name="creditreport",
            name="grade_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditreport",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creditreport",
            name="tlo_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
