# Generated by Django 4.1.7 on 2025-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transunion", "0003_creditreport_created_by_creditreport_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditreport",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
