# Generated by Django 4.1.7 on 2024-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers_user_address_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
