# Generated by Django 4.1.7 on 2024-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_nation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nation_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
