# Generated by Django 4.1.7 on 2024-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(blank=True, default="+254", max_length=5, null=True),
        ),
    ]
