# Generated by Django 4.1.7 on 2024-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_user_address_user_marital_status_user_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
