# Generated by Django 4.1.7 on 2025-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_marital_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("PHYSICAL", "Physical"),
                    ("POSTAL", "Postal"),
                    ("HEADQUARTERS", "Headquarters"),
                    ("OPERATING", "Operating"),
                    ("BRANCH", "Branch"),
                    ("REGISTERED", "Registered"),
                ],
                default="PHYSICAL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr.", "Mr."),
                    ("Mrs.", "Mrs."),
                    ("Miss", "Miss"),
                    ("Ms.", "Ms."),
                    ("Dr.", "Dr."),
                    ("Chief", "Chief"),
                    ("Sir", "Sir"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("user", "document_type")},
        ),
    ]
