# Generated by Django 4.1.7 on 2025-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_usertask_usertask_users_usert_user_id_659df4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_IDENTITY", "National Identity"),
                    ("NATIONAL_IDENTITY_BACK", "National Identity Back"),
                    ("FACIAL_PHOTO", "Facial Photo"),
                ],
                max_length=50,
            ),
        ),
    ]
