# Generated by Django 4.1.7 on 2025-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="district_of_birth",
            field=models.CharField(
                blank=True, max_length=180, null=True, verbose_name="district_of_birth"
            ),
        ),
    ]
