# Generated by Django 4.1.7 on 2025-02-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_district_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_IDENTITY", "National Identity"),
                    ("BACK_OF_NATIONAL_IDENTITY", "National Identity Back"),
                    ("FACIAL_PHOTO", "Facial Photo"),
                ],
                max_length=50,
            ),
        ),
    ]
