# Generated by Django 4.1.7 on 2025-06-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bridge_signed_agreement_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
