# Generated by Django 4.1.7 on 2025-06-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_bridge_signed_agreement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_IDENTITY", "National Identity"),
                    ("BACK_OF_NATIONAL_IDENTITY", "National Identity Back"),
                    ("FACIAL_PHOTO", "Facial Photo"),
                    ("SOCIAL_SECURITY_NUMBER", "Social Security Number"),
                    ("DRIVERS_LICENSE", "Drivers License"),
                    ("BACK_OF_DRIVERS_LICENSE", "Drivers License Back"),
                ],
                max_length=50,
            ),
        ),
    ]
