# Generated by Django 4.1.7 on 2025-06-09 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_country_state"),
        ("users", "0015_document_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="common.country",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="state_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="common.state",
            ),
        ),
    ]
