# Generated by Django 4.1.7 on 2025-06-12 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_occupation"),
        ("users", "0016_address_country_master_address_state_master"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bridge_signed_agreement_id",
        ),
        migrations.AddField(
            model_name="user",
            name="account_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Charitable Donations", "Charitable Donations"),
                    ("E-commerce Retail Payments", "E-commerce Retail Payments"),
                    ("Investment Purposes", "Investment Purposes"),
                    ("Operating a Company", "Operating a Company"),
                    ("Other", "Other"),
                    (
                        "Payments to Friends or Family Abroad",
                        "Payments to Friends or Family Abroad",
                    ),
                    ("Personal or Living Expenses", "Personal or Living Expenses"),
                    ("Protect Wealth", "Protect Wealth"),
                    ("Purchase Goods and Services", "Purchase Goods and Services"),
                    (
                        "Receive Payment for Freelancing",
                        "Receive Payment for Freelancing",
                    ),
                    ("Receive Salary", "Receive Salary"),
                ],
                max_length=128,
                null=True,
                verbose_name="account_purpose",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_purpose_other",
            field=models.CharField(
                blank=True,
                help_text="If 'Other' is selected, please specify the account purpose",
                max_length=255,
                null=True,
                verbose_name="account_purpose_other",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="acting_as_intermediary",
            field=models.BooleanField(
                default=False,
                help_text="Is the user acting as an intermediary for another person or entity?",
                verbose_name="acting as intermediary",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Employed", "Employed"),
                    ("Unemployed", "Unemployed"),
                    ("Student", "Student"),
                    ("Retired", "Retired"),
                    ("Homemaker", "Homemaker"),
                    ("Self Employed", "Self Employed"),
                ],
                max_length=128,
                null=True,
                verbose_name="employment_status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="expected_monthly_payments",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="expected monthly payments",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.ForeignKey(
                blank=True,
                help_text="Occupation of the user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="common.occupation",
                verbose_name="occupation",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="source_of_funds",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Company Funds", "Company Funds"),
                    ("E-commerce Reseller", "E-commerce Reseller"),
                    ("Gambling Proceeds", "Gambling Proceeds"),
                    ("Gifts", "Gifts"),
                    ("Government Benefits", "Government Benefits"),
                    ("Inheritance", "Inheritance"),
                    ("Investments/Loans", "Investments/Loans"),
                    ("Pension/Retirement", "Pension/Retirement"),
                    ("Salary", "Salary"),
                    ("Sale of Assets/Real Estate", "Sale of Assets/Real Estate"),
                    ("Savings", "Savings"),
                    ("Someone Else's Funds", "Someone Else's Funds"),
                ],
                max_length=128,
                null=True,
                verbose_name="account_purpose",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_IDENTITY", "National Identity"),
                    ("BACK_OF_NATIONAL_IDENTITY", "National Identity Back"),
                    ("FACIAL_PHOTO", "Facial Photo"),
                    ("SOCIAL_SECURITY_NUMBER", "Social Security Number"),
                    ("DRIVERS_LICENSE", "Drivers License"),
                    ("BACK_OF_DRIVERS_LICENSE", "Drivers License Back"),
                    ("PASSPORT", "Passport"),
                    ("BACK_OF_PASSPORT", "Passport Back"),
                ],
                max_length=50,
            ),
        ),
    ]
