# Generated by Django 4.1.7 on 2025-06-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_remove_user_bridge_signed_agreement_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="acting_as_intermediary",
            field=models.BooleanField(
                blank=True,
                help_text="Is the user acting as an intermediary for another person or entity?",
                null=True,
                verbose_name="acting as intermediary",
            ),
        ),
    ]
