# Generated by Django 4.1.7 on 2025-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_acting_as_intermediary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("NATIONAL_IDENTITY", "National Identity"),
                    ("BACK_OF_NATIONAL_IDENTITY", "National Identity Back"),
                    ("FACIAL_PHOTO", "Facial Photo"),
                    ("SOCIAL_SECURITY_NUMBER", "Social Security Number"),
                    ("DRIVERS_LICENSE", "Drivers License"),
                    ("BACK_OF_DRIVERS_LICENSE", "Drivers License Back"),
                    ("PASSPORT", "Passport"),
                    ("BACK_OF_PASSPORT", "Passport Back"),
                    ("BANK_STATEMENT", "Bank Statement"),
                    ("UTILITY_BILL", "Utility Bill"),
                    ("GOVERNMENT_ISSUED_LETTER", "Government Issued Letter"),
                    ("RESIDENTIAL_LEASE_AGREEMENT", "Residential Lease Agreement"),
                ],
                max_length=50,
            ),
        ),
    ]
