name: Deploy to EC2

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV_BASE64_DJANGO: ${{ secrets.ENV_BASE64_DJANGO }}
    steps:
      - uses: actions/checkout@v3

      - name: Decode and create .env files
        run: |
          mkdir -p ./.envs/.production/
          echo "${{ env.ENV_BASE64_DJANGO }}" | base64 --decode > combined.env.django
          cp combined.env.django ./.envs/.production/.django

      - name: Create Docker Network
        run: docker network create reverseproxy_nw || true

      - name: Build Docker images
        run: docker compose -f production.yml up --build -d --remove-orphans

      - name: Debugging - List files in current directory
        run: ls -lah

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e  # Exit on first error

            echo "** Connected to EC2 server **"

            # Ensure Git is installed
            if ! command -v git &> /dev/null
            then
                echo "Git could not be found, installing..."
                sudo apt-get update && sudo apt-get install git -y
            fi

            # Check if app directory exists. If so, prepare to update the repo
            if [ -d "/app" ]; then
              echo "** /app directory exists. Fetching latest changes... **"
              cd /app
              # Fetch the latest changes without affecting the working directory
              sudo git fetch origin dev
              sudo git reset --hard origin/dev
              sudo git clean -fd
            else
              # Clone the repository if /app does not exist
              echo "** Cloning repository into /app... **"
              sudo git clone -b dev git@github.com:RudreshNarwal/folo.django.git /app
            fi

            cd /app

            # Here, include any steps required to prepare the application environment,
            # such as running migrations, compiling assets, etc.

            echo "** Building and starting Docker containers... **"
            sudo docker compose -f production.yml up --build -d --remove-orphans || (echo "** Docker Compose failed! **" && exit 1)

            echo "** Deployment completed successfully! **"
